### ISSUE TITLE
Compatibility with OMNET++ 5.0

### ISSUE THREAD

**Issue by brtknr** [floxyz/veins-lte#1]
Hi there,

There appears to be compatibility issue with the new version of OMNET. Which version was this built on? And how can I make it compatible?

Regards

**Comment by floxyz** [comment]
Hi,

the current version of Veins LTE is for OMNeT++ 4.6.


Best

**Comment by brtknr** [comment]
Great, thanks for letting me know!

**Comment by gabrielbiasi** [comment]
I'm sorry for re-open the issue @floxyz , but which version of SUMO should I have to use aswell? You don't specified on the README.
