### ISSUE TITLE
Running error (Invalid speed distribution)

### ISSUE THREAD

**Issue by itismeaso** [floxyz/veins-lte#11]

**Comment by itismeaso** [comment]
Hello michele-segate, 

I am trying to run the plexe examples, I followed all the instructions on the web page (adding the path and all the rest...).
When I am trying to run the simulation from the terminal, I am getting the following error; 

"Error: Invalid speed distribution when parsing vType 'vtypeauto' (distribution mean 1000.00 is larger than upper boundary 2.00)"

I very much appreciate if you please advice, thanks very much for your time in advance. 
Best Regards.

**Comment by sommer** [comment]
You are writing this in the issue tracker of Veins LTE. You are likely looking for a support forum for Plexe.

**Comment by itismeaso** [comment]
so sorry,
