### ISSUE TITLE
dblrand

### ISSUE THREAD

**Issue by ZOGHLAMIChaima** [floxyz/veins-lte#12]
In ExampleDecisionMaker there is an if condition in sendDontCareMessage based on a comparison on dblrand() with 0.5.  (I found that this function generates a random double in [0,1) )  can you please explain what does it signify so that I could understand when exactly the LTE messages are sent?

**Comment by floxyz** [comment]
Hi,

this was just an example where to implement functionality. In this case it just sent a message via LTE 50% of the time and 50% via IEEE 802.11p.
Please note that Veins LTE is not actively developed right now - for up-to-date versions of the used software, please refer to [SimuLTE](https://simulte.com/) and [Veins](https://veins.car2x.org/)_
