### ISSUE TITLE
Veins-LTE :- Vertical Handover 

### ISSUE THREAD

**Issue by pranav-k-singh** [floxyz/veins-lte#6]
Is it possible to implement vertical handover using this module in HetNet ?
Plz Help

**Comment by floxyz** [comment]
Hi,
yes, it is possible to do this.
But note that this functionality is currently not implemented - you have to write the decision process yourself.
The `DecisionMaker` modules provide the entry point for your implementation of such a handover mechanism.

**Comment by pranav-k-singh** [comment]
OK Thank you so much.
