### ISSUE TITLE
Error OMNeT++ 4.6 and 5 with parameter 'debug': already defined in DecisionMaker.ned 

### ISSUE THREAD

**Issue by scmdmo** [floxyz/veins-lte#7]
After import the project add "the with INET framework" and configure references of veins to use inet and simulte using OMNeT 4.6, it show me a error about property debug in /veins/src/veins/modules/lte/DecisionMaker.ned ->
'debug': already defined at /veins/src/veins/modules/application/ieee80211p/BaseWaveApplLayer.ned:37

DecisionMaker.ned define a boolean debug parameter but this parameter is already defined in its parent class BaseWaveApplLayer, so they have a conflict.

```
simple DecisionMaker extends BaseWaveApplLayer {
	parameters:
		@class(DecisionMaker);

		bool debug = default(false);
		bool infoLogging = default(true);
```
------------------------------------------------------------------
```
simple BaseWaveApplLayer like IBaseApplLayer
{
    parameters:
        bool debug = default(false); //whether to print debug output
        int headerLength = default(88bit) @unit(bit); //header length of the application
```

I tried with OMNeT 5 too but the 'debug' issue still continue.

**Comment by floxyz** [comment]
Hi, does this error also occur if you build Veins LTE from the command line?

I want to make sure if this is a general issue or one related to the IDE.

**Comment by scmdmo** [comment]
Hi, I think it's related to the IDE. Command line compilation works fine. Only warnings appear.

**Comment by floxyz** [comment]
Thanks for the update. I will look into it.

**Comment by compuram** [comment]
Hi, I built VeinsLTE using the OMNET++ IDE and am encountering the following error:

'debug': already defined at /veins/src/veins/modules/application/ieee80211p/BaseWaveApplLayer.ned: 37

I am using the IDE. Can you please let me know how to resolve this error? 

I appreciate your response.

**Comment by FarnoushFR** [comment]
Hi, 
I am using ubuntu 18.04, I installed Omnet 5.3 and Sumo 0.32 . I do not use IDE, I tried to install Veinslte but I have received many problems during installation of latest version of VeinsLte which I have downloaded via : http://veins-lte.car2x.org/installation/
Many thanks for any guidance...

**Comment by FarnoushFR** [comment]
It is the error that I have:

make -C inet
make[1]: Entering directory '/home/farnoushu/veins-lte-1.3/veins-lte-master/inet'
cd src && make
make[2]: Entering directory '/home/farnoushu/veins-lte-1.3/veins-lte-master/inet/src'
applications/common/ApplicationBase.cc
In file included from applications/common/ApplicationBase.cc:18:0:
applications/common/ApplicationBase.h:21:10: fatal error: OperationalBase.h: No such file or directory
 #include "OperationalBase.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:784: recipe for target '../out/gcc-release/src/applications/common/ApplicationBase.o' failed
make[2]: *** [../out/gcc-release/src/applications/common/ApplicationBase.o] Error 1
make[2]: Leaving directory '/home/farnoushu/veins-lte-1.3/veins-lte-master/inet/src'
Makefile:2: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/farnoushu/veins-lte-1.3/veins-lte-master/inet'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

I appreciate any help

**Comment by WemyJu** [comment]
This project looks like not support for the latest version OMNeT++ and SUMO. I change to use old version of everything, now it's executable on my machine. 
Here are the environment I use:
OMNeT++:  4.6 (It looks like the structure of the project has changed since version 5.)
Java: 1.8 (Java 8) for the eclipse used for OMNeT++
SUMO: 0.26 (There would be an error if the API version is not 10 or 11, which is SUMO 0.25 or 0.26.)
g++: 4.2 (It looks like the g++ version higher than 5 would get "flexible array member in union" error)

**Comment by floxyz** [comment]
That is correct, OMNeT++ 4.6 and SUMO 0.25 are the currently supported versions. If I have time I will update it with newest OMNeT, Veins and SimuLTE features. But as there are some major version steps, the changes are not trivial to add.

**Comment by FarnoushFR** [comment]
Thank you for your responds. Yes, I switched to OMNeT++ 4.6 and SUMO 0.25 on Ubuntu 16.04, but as @WemyJu mentioned, it has problem with API version and it is recommended to use SUMO 0.26. So, I removed SUMO 0.25 and have installed SUMO 0.26 but still I have same problem as following:
Assigned runID=nodebug-9-20180807-11:53:52-2820
Setting up network `scenario'...
Initializing...

Running simulation...
** Event #1   T=0   Elapsed: 0.000s (0m 00s)  0% completed
     Speed:     ev/sec=0   simsec/sec=0   ev/simsec=0
     Messages:  created: 11   present: 11   in FES: 7
** Event #2   T=0   Elapsed: 0.011s (0m 00s)  0% completed
     Speed:     ev/sec=181.818   simsec/sec=0   ev/simsec=0
     Messages:  created: 11   present: 10   in FES: 5

<!> Error in module (Veins::TraCIScenarioManagerForker) scenario.manager (id=6) at event #2, t=0: Model error: TraCI server "sumo-launchd.py 1.00" reports API version 1, which is unsupported. We recommend using SUMO 0.26.0.

Clear all sockets
Loading configuration... done.
Error: tcpip::Socket::accept() Unable to create listening socket: Address already in use
Quitting (on error).

End.
I am grateful for any help.

**Comment by WemyJu** [comment]
Is this bug caused by running the heterogenous example or other project?
When I executing the heterogenous example, I only have event #1, and than execute correctly. It looks like the problem happens on event #2 that OMNeT++ doesn't send the correct format of initialization packet to SUMO.

**Comment by FarnoushFR** [comment]
Yes, it is from running heterogeneous example of Veinslte.
Actually, I am beginner in OMNeT++ and Veinslte... do you think if I only execute event #1 I will not see this bug again? If yes, how can I limit execution of events in this example?
Thank you in advance.

**Comment by WemyJu** [comment]
I am also the beginner for Veins LTE, so I'm not sure how to control it to make it only run for one event. However, according to my understanding of "sumo-launch.py" and Sumo0.32, your error message looks like sending from "sumo-launch.py" file that it doesn't think you're using the right version of Sumo. (Since it showed that you're using API 1, I guess this might cause by packet format error that it can't get the correct version of Sumo.)

**Comment by floxyz** [comment]
As OMNeT++ is processing event after event, it will not suffice to only run event 1. I can recommend the  [https://docs.omnetpp.org/tutorials/tictoc/](TicToc tutorial) to understand how to use OMNeT++. It is however strange that SUMO reports version 1, maybe you are not using SUMO v25 or v26 after all...
What is the output if you type `sumo --version`? It should be something like `SUMO Version 0.25.0`.

**Comment by FarnoushFR** [comment]
It is the output from sumo --version :+1: 

farnoush@farnoush-vmachine:~$ sumo --version
SUMO Version 0.26.0
 Build features: x86_64-unknown-linux-gnu InternalLanes DoublePrecision TRACI PROJ GDAL GUI
 Copyright (C) 2001-2016 DLR and contributors; http://sumo.dlr.de

SUMO Version 0.26.0 is part of SUMO.
SUMO is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/gpl.html
------------------------------------------------------------

Thank you.

**Comment by FarnoushFR** [comment]
It is a part of my "sumo-launchd.py" file that shows _API_VERSION=1:

<?xml version="1.0"?>
<launch>
  <basedir path="/home/farnoush/veins-lte-master/veins/examples/heterogeneous" />
  <seed value="1" />
  <copy file="heterogeneous.net.xml" />
  <copy file="heterogeneous.rou.xml" />
  <copy file="heterogeneous.sumo.cfg" type="config" />
  
</launch>
"""

import os
import sys
import tempfile
import shutil
import socket
import struct
import subprocess
import time
import signal
import exceptions
import thread
import xml.dom.minidom
import select
import logging
import atexit
from optparse import OptionParser

_API_VERSION = 1
_LAUNCHD_VERSION = 'sumo-launchd.py 1.00'
_CMD_GET_VERSION = 0x00
_CMD_FILE_SEND = 0x75

**Comment by FarnoushFR** [comment]
Hi @WemyJu 
Thank you for your help...Yes your right, I dont have problem when I just run heterogeneous example without running sumo-launchd.py. But in case that I want use SUMO in my work, I need to solve problem.
Do you know, in heterogeneous example If I need to change number of nodes (vehicles) where I can modify it? And about the results, If I need to calculate a parameter and see it in results where I must to add my formula and where I have to write code to show it in result file? (I am running this example in command not in IDE because it has bugs in the case of running in IDE of OMNeT++)
I appreciate for any help.

**Comment by FarnoushFR** [comment]
Hello again,
I am working on heterogeneous example of veinslte and I need to have two RUs in my simulation scenario. So, I changed value of "num.Rus" from "0" to "2" in omnetpp.ini file (in Deployer Parameters part of this file). But after running, I have following error: 

<!> Error in module (LteDeployer) scenario.eNodeB1.deployer (id=17) during network initialization: parseStringToIntArray(): more values in string than nodes.

Clear all sockets

Does any body knows how can I solve it?
Any help is appreciated.

**Comment by FarnoushFR** [comment]
Hi,
In heterogeneous example of Veinslte, is it possible to add RSU (road side unit) in order to create wireless communication between vehicles and RSU ?

Thank you.

**Comment by VasiKydo** [comment]
Hi to all!
I have read all the conversation above but I still can't understand how the issue with "debug" is solved. I couldn't build Veins LTE from command line, so I tried with the IDE. Any help? Would help a lot!

**Comment by floxyz** [comment]
Hi VasiKydo,

the issue was that the example was run from the IDE - and that did not work. As stated in the Readme and in this thread, building, and especially running, from the command line was the way to go.
Nevertheless, I recommend looking into [Veins](https://veins.car2x.org/) and [SimuLTE](https://simulte.com/) as there is no active development of Veins LTE at the moment and this two project are still active.
